<Workspace Version="0.8.3.2305" X="0" Y="0" zoom="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSFunction guid="ff7c111a-9c3d-4e2f-bebf-fe7c430e13f2" type="Dynamo.Nodes.DSFunction" nickname="Sphere.CenterPoint" x="358.5" y="144.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Sphere.CenterPoint" />
    <Dynamo.Nodes.DSFunction guid="0216c7f8-3887-4047-82e9-ac52fba11cea" type="Dynamo.Nodes.DSFunction" nickname="Sphere.Radius" x="349.5" y="233.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Sphere.Radius" />
  </Elements>
  <Connectors />
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>